#!/usr/bin/env python
# ------------------------------------------------------------------------------
# switch_costmap_profile
# ------------------------------------------------------------------------------
# Script to shuffle costmap parameters in and out of different directories.
# ------------------------------------------------------------------------------
# Author: David Tsai (david.tsai@simberobotics.com)
# Copyright (c) 2018, Simbe Robotics, Inc.
# ------------------------------------------------------------------------------

import os
import shutil
import argparse


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("profile_name", type=str)
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    args = get_args()
    profile_name = args.profile_name

    print("Switching costmap profile to {0}".format(profile_name))

    costmap_param_dir = "/opt/simbe/tally/share/tally_nav/param"
    profile_dir = os.path.join(costmap_param_dir, profile_name)
    for filename in os.listdir(profile_dir):
        profile_param_filename = os.path.join(profile_dir, filename)
        shutil.copy(profile_param_filename, costmap_param_dir)

    print("Switching complete, restart move_base to use new params")
